version: '3.8'

services:
  nginx:
    image: nginx
    networks:
      - app
    ports:
    - 8888:8888
    depends_on:
      - backend

  frontend:
    container_name: main_frontend
    image: node:14
    networks:
      - app
    depends_on:
      - backend


  backend:
    container_name: main_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: main
      DB_USERNAME: root
      DB_PASSWORD: ''
    ports:
    - 8000:8000
    volumes:
    - .:/app
    networks:
      - app
    depends_on:
      - db

  db:
    container_name: main_db
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    volumes:
    - .dbate:/var/lib/mysql
    ports:
    - 33068:3306
    networks:
      - app

networks:
  app:

